services:
  # Nginx - веб-сервер с проксированием запросов /api на PHP-сервис
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./templates:/etc/nginx/templates
      - ./../../public:/var/www/public
    ports:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      - api
      - frontend
    environment:
      - NGINX_HOST=${NGINX_HOST:-localhost}
      - API_HOST=api
      - API_PORT=8000
    networks:
      - crm_network
