# https://hub.docker.com/_/rabbitmq
services:
  rabbitmq:
    image: rabbitmq:4-management-alpine
    restart: unless-stopped
    env_file:
      - path: .env
      - path: ../.env
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  rabbitmq:
