services:
  ### SERVICES
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - path: .env
      - path: ../.env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ../../:/var/www
    working_dir: /var/www
    expose:
      - "9000"
    depends_on:
      db:
        condition: service_healthy
#      rabbitmq:
#        condition: service_healthy
#      redis-master:
#        condition: service_healthy
    networks:
      - crm_network

volumes:
  backend_bash_history_volume:
