# https://hub.docker.com/_/postgres
services:
  db:
    image: postgres:latest
    restart: unless-stopped
    shm_size: 128mb
    env_file:
      - path: .env
      - path: ../.env
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - crm_network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
volumes:
  db:
